version: 2

sources:
  - name: SALES
    tables:
      - name: raw_customer
      - name: raw_product
      - name: raw_customer_product

models:
  - name: customer
    config:
      materialized: incremental
      unique_key: customer_id
      incremental_strategy: merge

  - name: product
    config:
      materialized: incremental
      unique_key: product_id
      incremental_strategy: merge

  - name: customer_product
    config:
      materialized: incremental
      unique_key: customer_product_hk
      incremental_strategy: merge

  - name: hub_customer
    config:
      materialized: incremental
      unique_key: customer_hk

  - name: hub_product
    config:
      materialized: incremental
      unique_key: product_hk

  - name: link_customer_product
    config:
      materialized: incremental
      unique_key: customer_product_hk

  - name: sat_customer
    config:
      materialized: incremental
      unique_key: customer_hk

  - name: sat_product
    config:
      materialized: incremental
      unique_key: product_hk